### ISSUE TITLE
Auto hide leads to crash

### ISSUE THREAD

**Issue by KingKnecht** [countincognito/Zametek.PrismEx.AvalonDock#1]
Hi,
I'm investigating your solution and found a bug. If "Auto hide" is used (the pinning symbol) the pane hides at the side of the app. But if mouse goes over the "hidden" pane the app crashes.
I tried to debug this to find the problem but without success.
Any ideas on this?
Thx,
Sven

**Comment by KingKnecht** [comment]
Found the answer:
Tools > Options > Debugging > General > Enable UI Debugging Tools for XAML

It's the debugger causing the crash...

**Comment by countincognito** [comment]
Hi - thanks for flagging this up. I'll see if I can find out how it can be prevented.
